
server.port=8011
server.address=0.0.0.0


spring.datasource.url=jdbc:postgresql://localhost:5432/fut-sumula-torneio-db
spring.datasource.username=postgres
spring.datasource.password=admin


spring.jpa.hibernate.ddl-auto=update